/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tablechair_groupproject;

/**
 *
 * @author strotheb6455
 */
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class OrderForm
        extends javax.swing.JFrame
{

    /**
     * Creates new form OrderForm
     */
    public OrderForm()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitOrder = new javax.swing.JButton();
        quit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Order_Form = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        num_chairsTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        promo_box = new javax.swing.JComboBox<>();
        shipping_typeBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        distanceTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        order_nameTF = new javax.swing.JTextField();
        Order_addressTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        paymentType_Box = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        num_tablesTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(30, 198, 79));
        getContentPane().setLayout(null);

        submitOrder.setText("Submit");
        submitOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitOrderActionPerformed(evt);
            }
        });
        getContentPane().add(submitOrder);
        submitOrder.setBounds(114, 535, 73, 25);

        quit.setText("Quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        getContentPane().add(quit);
        quit.setBounds(321, 535, 55, 25);

        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("How many chairs will you need?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(9, 121, 183, 14);

        Order_Form.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Order_Form.setForeground(new java.awt.Color(153, 255, 255));
        Order_Form.setText("Order Form");
        getContentPane().add(Order_Form);
        Order_Form.setBounds(162, 13, 124, 57);

        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("Select shipping type");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(82, 309, 114, 16);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Shipping");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 190, 52, 29);

        num_chairsTF.setText("0");
        getContentPane().add(num_chairsTF);
        num_chairsTF.setBounds(227, 117, 95, 22);

        jLabel4.setForeground(new java.awt.Color(0, 204, 255));
        jLabel4.setText("Promo codes");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(115, 456, 74, 16);

        promo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Military", "Student", "Senior" }));
        getContentPane().add(promo_box);
        promo_box.setBounds(283, 453, 70, 22);

        shipping_typeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Day Shipping", "2 Day Shipping", "Free Shipping - 5 Day", "Pick Up" }));
        getContentPane().add(shipping_typeBox);
        shipping_typeBox.setBounds(246, 306, 151, 22);

        jLabel5.setForeground(new java.awt.Color(153, 204, 255));
        jLabel5.setText("Distance to Venue in miles");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(82, 269, 151, 16);
        getContentPane().add(distanceTF);
        distanceTF.setBounds(246, 266, 63, 22);

        jLabel6.setForeground(new java.awt.Color(102, 204, 255));
        jLabel6.setText("Shipping Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(134, 234, 99, 16);

        jLabel7.setForeground(new java.awt.Color(0, 153, 204));
        jLabel7.setText("Order name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(74, 80, 69, 16);
        getContentPane().add(order_nameTF);
        order_nameTF.setBounds(227, 77, 95, 22);
        getContentPane().add(Order_addressTF);
        Order_addressTF.setBounds(246, 231, 100, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 204, 255));
        jLabel8.setText("Payment");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(193, 348, 55, 17);

        jLabel9.setForeground(new java.awt.Color(51, 204, 255));
        jLabel9.setText("Payment Type");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(115, 398, 81, 16);

        paymentType_Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Credit", "Debit" }));
        getContentPane().add(paymentType_Box);
        paymentType_Box.setBounds(283, 395, 61, 22);

        jLabel11.setForeground(new java.awt.Color(0, 204, 255));
        jLabel11.setText("How many tables will you need?");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(9, 155, 183, 16);

        num_tablesTF.setText("0");
        getContentPane().add(num_tablesTF);
        num_tablesTF.setBounds(227, 152, 95, 22);

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\Advanced Java\\TableChair_GroupProject_11-30-22\\tablesImg.png")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-12, 0, 750, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitOrderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_submitOrderActionPerformed
    {//GEN-HEADEREND:event_submitOrderActionPerformed
        String order_name;
        String shipping_address;
        String discount;
        String shipping_type;
        double distance;
        int num_chairs;
        int num_tables;
        int getNumTables;
        int getNumChairs;
        double total;
        double tenOff;
        double fifteenOff;
        double twentyOff;
        
        order_name = order_nameTF.getText();
        num_chairs = Integer.parseInt(num_chairsTF.getText());
        num_tables = Integer.parseInt(num_tablesTF.getText());
        shipping_address = Order_addressTF.getText();
        distance = Double.parseDouble(distanceTF.getText());
        discount = String.valueOf(promo_box.getSelectedItem());
        shipping_type = String.valueOf(shipping_typeBox.getSelectedItem().toString());
        if (num_chairs == 0)
        {
            getNumChairs = ((num_tables)*2) +2;
            num_chairs = getNumChairs;
        }
        if (num_tables == 0)
        {
            getNumTables = ((num_chairs)/2) -1;
            num_tables = getNumTables;
            
        }
        
        total = num_chairs * 10 + num_tables * 20;
        
        if (discount == "Military"){
            tenOff = total * .10;
            total = total - tenOff;
        }
        
        else if (discount == "Student"){
            fifteenOff = total * .15;
            total = total - fifteenOff;
        }
        
        else if (discount == "Senior"){
            twentyOff = total * .20;
            total = total - twentyOff;
        }
        else{
            
        }
        
        
        
        JOptionPane.showMessageDialog(null, "Thank you " + order_name + "\n"
                + "You have ordered " + num_chairs + " chairs" + "\n"
                + "You have ordered " + num_tables + " tables" + "\n"
                + "Address: " + shipping_address + "\n"
                + "Shipping Type: " + shipping_type + "\n"
                + "Distance to venue in miles: " + distance + "\n"
                + "The total for this order is $"+ String.format("%.2f", total));
        
        dispose();
    
        try {
            print(order_name, distance, shipping_address, shipping_type, num_chairs, num_tables, total);
        } 
        catch (IOException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_submitOrderActionPerformed
    
    public static void print(String order_name,double distance, String shipping_address, String shipping_type,int num_chairs, int num_tables, double total) throws IOException{
        PrintWriter outputfile = new PrintWriter(order_name+" Billing.txt");
        outputfile.println("Thank you " + order_name + "\n"
                + "You have ordered " + num_chairs + " chairs" + "\n"
                + "You have ordered " + num_tables + " tables" + "\n"
                + "Address: " + shipping_address + "\n"
                + "Shipping Type: " + shipping_type + "\n"
                + "Distance to venue in miles: " + distance + "\n"
                + "The total for this order is $"+ String.format("%.2f", total));
        outputfile.close();
        }

    private void quitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_quitActionPerformed
    {//GEN-HEADEREND:event_quitActionPerformed
        dispose();
    }//GEN-LAST:event_quitActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new OrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Order_Form;
    private javax.swing.JTextField Order_addressTF;
    private javax.swing.JTextField distanceTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField num_chairsTF;
    private javax.swing.JTextField num_tablesTF;
    private javax.swing.JTextField order_nameTF;
    private javax.swing.JComboBox<String> paymentType_Box;
    private javax.swing.JComboBox<String> promo_box;
    private javax.swing.JButton quit;
    private javax.swing.JComboBox<String> shipping_typeBox;
    private javax.swing.JButton submitOrder;
    // End of variables declaration//GEN-END:variables
}
